name: lesson_newsapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  nested: ^1.0.0
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  http: ^1.0.0
  flutter_advanced_drawer: ^1.3.5
  json_annotation: ^4.8.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/.
    - assets/json/.
    - assets/fonts/Josefin Sans/.